export interface User {
  id: number,
  name: string,
  api_key: string,
  kimi_account_id: string,
  phone: string,
  balance: number,
  request_made: number,
  buy_fee_margin: number,
  sell_fee_margin: number,
  group: any,
  last_seen: string,
  remember_token: string,
  last_login_at: string,
  last_login_ip: string,
  deleted_at: string,
  created_at: string,
  updated_at: string,
  inquiry_access: boolean,
  has_pass: boolean,
  market_opening_notification: string,
  aggregated_view_of_invoices: string,
}
